### ISSUE TITLE
Failed to download the `masif_test.tar.gz`

### ISSUE THREAD

**Issue by zhaisilong** [stebliankin/piston#1]
<https://users.cs.fiu.edu/~vsteb002/piston/masif_test.tar.gz>

Not Found

The requested URL was not found on this server.

**Comment by stebliankin** [comment]
I apologize; the dataset has been moved to the Zenodo server. Please use the following link instead: https://zenodo.org/record/7948337/files/masif_test.tar.gz?download=1
